"""Streamlit portfolio showcase for EfficientAT and our trained classifier.

Run with: python -m streamlit run app.py
"""
import base64
import html
import hashlib
import io
import json
from pathlib import Path
from tempfile import TemporaryDirectory
from threading import RLock

import streamlit as st

from showcase import (
    ROOT, DEFAULT_OUTPUT, FONT_DIR, MODEL_PATH, EMPTY, analyze, confusion_figure,
    distribution_figure, local_examples, read_csv,
)

HERO = '<div class="hero"><h1>Listen. Measure. Inspect.</h1><p>Explore how a pretrained audio encoder and our trained classifier assess a recording.</p><span class="small-note">EfficientAT mn10_as + logistic regression | 960 learned audio features</span></div>'

RESULTS_INTRO = """## How the encoder model performed
We trained our classifier on **700 recordings**, used **150 for validation**, and evaluated it on another **150: 75 human and 75 AI recordings**. The EfficientAT encoder stayed frozen throughout.

Related reference artists stay in one split. The evaluation recordings were also used in earlier experiments, so these results are a reused benchmark, not a new blind test.
"""

SCORES_INTRO = '### Where the scores fall\nEach dot is one recording. The line at 0.5 is the decision threshold. Human recordings to its right are false positives; AI recordings to its left are missed detections. These scores are not confidence percentages.'

LIMITATIONS = '**Where this model is limited:** it still makes mistakes. Dataset source, encoding and genre may influence predictions. Evaluation covers Rock and Electronic, with no Pop. Microphone recordings, room noise and unfamiliar generators have not been validated. Dataset labels are not proof of authorship.'

HOW_IT_WORKS = """## From a recording to an AI score
### 1. Choose sections across the recording
We convert the audio to mono at **32 kHz**, then select up to **five 20-second sections** from different parts of the recording. The random seed stays fixed, so analyzing the same file again selects the same sections. Sections may overlap; files shorter than 20 seconds use all available audio.

### 2. Let EfficientAT describe the sound
**EfficientAT mn10_as is a pretrained audio encoder.** It turns each section's mel spectrogram into a list of **960 numbers**, called an embedding. Think of it as a learned description of the sound. We average the section embeddings into one description of the recording.

These numbers are not named measurements such as loudness, nor do individual numbers reliably mean guitar or vocals. The information is spread across the embedding. The encoder itself does not decide whether music is human or AI-generated.

### 3. Apply the classifier we trained
We trained **our own logistic-regression classifier** on embeddings from labeled human and AI recordings. A scaler first puts the embedding values on the scales learned from training data. The classifier combines 960 weighted values and an intercept; a sigmoid turns that total into an AI score between 0 and 1.

The encoder weights stay unchanged: only our scaler and classifier learn from the project's training recordings.

### 4. Read the result
A score **at or above 0.5** produces **Likely AI-generated**; a lower score produces **Likely human-made**. A score of 0.9 does not establish a 90% chance of AI authorship. These scores have not been calibrated, and the model does not yet offer an inconclusive result.

### What we trained on
**1,000 recordings: 500 human references and 500 generated recordings.** Human labels come from historical FMA recordings; AI labels come from Echoes TTA, covering 12 generators. The split is **700 training, 150 validation and 150 evaluation**, with equal class counts in each. Only the training split fits the scaler and classifier. Validation guides model selection; evaluation has been reused across experiments.

### What the visuals explain
**Waveform:** where the sampled sections are located. **Spectrogram:** the frequencies in the first sampled section, shown for inspection. The encoder computes its own mel spectrogram internally; this displayed plot is not the image fed into the model.

**Contribution chart:** how the classifier used the averaged embedding. We show the ten dimensions with the largest absolute contributions, combine the other 950 into one bar, and include the intercept. Teal pushes toward human; amber pushes toward AI. All bars sum to the classifier's raw total, called a logit, before the sigmoid.

A label such as **Embedding 623** is a coordinate in a learned representation, not a named musical property. This chart explains the classifier's arithmetic; it does not reveal exactly what the encoder heard or prove that an audible detail was generated by AI.

**Built with** NumPy, SciPy, PyTorch, scikit-learn and Streamlit. The encoder and classifier run on the app server without a paid inference API.
"""

CONTRIBUTION_GUIDE = "These bars show how our classifier used the encoder's 960-number description. The ten strongest dimensions are shown separately; the other 950 are summed into one bar. Teal pushes toward human and amber toward AI. Dimension numbers are not named audio properties. The bars and intercept sum to the raw score (logit) before it becomes an AI score."

INPUT_GUIDANCE = '**10 seconds to 5 minutes, up to 50 MB.** EfficientAT encodes up to five random 20-second sections; our trained classifier scores their average embedding. Uploads are processed on the app server.'


@st.cache_data(show_spinner=False)
def stylesheet(css_version):
    """Bundle local fonts; the browser makes no third-party font requests."""
    fonts = []
    for name, weight in [('Regular', 400), ('SemiBold', 600), ('Bold', 700)]:
        encoded = base64.b64encode((FONT_DIR / f'IBMPlexMono-{name}.ttf').read_bytes()).decode('ascii')
        fonts.append(f"@font-face {{font-family:'IBM Plex Mono';src:url(data:font/ttf;base64,{encoded}) format('truetype');font-weight:{weight};font-display:swap;}}")
    return '<style>' + ''.join(fonts) + (ROOT / 'assets/streamlit.css').read_text(encoding='utf-8') + '</style>'


@st.cache_resource
def analysis_lock():
    # Matplotlib is shared by sessions; serialize plotting and bound decode concurrency.
    return RLock()


def figure_png(figure):
    output = io.BytesIO()
    figure.savefig(output, format='png', dpi=130, facecolor=figure.get_facecolor())
    figure.clear()
    return output.getvalue()


def run_analysis(data, name):
    """Decode an isolated temporary file and delete it even when analysis fails.

    Only this browser session retains the result and original playback bytes.
    Uploaded audio is never placed in Streamlit's shared cache.
    """
    if len(data) > 50 * 1024 * 1024:
        return ('<div class="result-card"><h2>Could not analyze this recording</h2>'
                '<p>Please choose a recording smaller than 50 MB.</p></div>', '', None, None, None, [])
    with analysis_lock(), TemporaryDirectory(prefix='music-detector-') as directory:
        path = Path(directory) / ('recording' + Path(name).suffix.lower())
        path.write_bytes(data)
        verdict, details, original, signal, influence, rows = analyze(path, display_name=name)
        return (verdict, details, data if original else None,
                figure_png(signal) if signal is not None else None,
                figure_png(influence) if influence is not None else None, rows)


def clear_result():
    st.session_state.pop('analysis_result', None)
    st.session_state.pop('playback_format', None)


def upload_changed():
    clear_result()
    st.session_state['example'] = None


def example_changed():
    clear_result()
    # A new uploader key clears the previously uploaded file unambiguously.
    st.session_state['upload_generation'] = st.session_state.get('upload_generation', 0) + 1



def responsive_plot(data, caption):
    """Keep plot labels readable on phones with a locally scrollable figure."""
    encoded = base64.b64encode(data).decode('ascii')
    label = html.escape(caption, quote=True)
    st.html(f'<figure class="responsive-plot"><div class="plot-scroll" tabindex="0" role="region" aria-label="{label}">'
            f'<img src="data:image/png;base64,{encoded}" alt="{label}"></div>'
            f'<figcaption>{label}</figcaption></figure>')


def numeric_table(headers, rows):
    """Accessible HTML table keeps numeric values right-aligned and monospace."""
    head = ''.join(f'<th scope="col">{html.escape(value)}</th>' for value in headers)
    body = []
    for row in rows:
        cells = []
        for value in row:
            numeric = isinstance(value, (float, int))
            rendered = f'{value:.6g}' if numeric else str(value)
            cells.append(f'<td class="{"number" if numeric else "text"}">{html.escape(rendered)}</td>')
        body.append('<tr>' + ''.join(cells) + '</tr>')
    st.html('<div class="table-scroll" tabindex="0" role="region" aria-label="Scrollable data table"><table class="values-table"><thead><tr>' + head +
            '</tr></thead><tbody>' + ''.join(body) + '</tbody></table></div>')


@st.cache_data(show_spinner=False)
def evaluation_artifacts(model_version):
    metrics = json.loads((DEFAULT_OUTPUT / 'metrics.json').read_text(encoding='utf-8'))['metrics']
    predictions = read_csv(DEFAULT_OUTPUT / 'predictions.csv')
    with analysis_lock():
        confusion = figure_png(confusion_figure(metrics))
        distribution = figure_png(distribution_figure(predictions))
    return metrics, predictions, confusion, distribution


def render_analysis():
    left, right = st.columns([1, 1.65], gap='large')
    with left:
        upload = st.file_uploader('Your recording', type=['wav', 'mp3', 'flac', 'ogg'],
                                  key=f'upload_{st.session_state.get("upload_generation", 0)}',
                                  on_change=upload_changed, max_upload_size=50)
        examples, labels = local_examples()
        example = None
        if examples:
            example = st.selectbox('Try an existing recording, then press Analyze',
                                   options=range(len(examples)), index=None,
                                   format_func=lambda index: labels[index], key='example',
                                   on_change=example_changed)
        ###st.markdown(INPUT_GUIDANCE)
        if st.button('Analyze recording', type='primary', width='stretch'):
            clear_result()
            if upload is not None or example is not None:
                with st.spinner('Analyzing recording...'):
                    if upload is not None:
                        data, name = upload.getvalue(), upload.name
                    else:
                        path = Path(examples[example][0])
                        data, name = path.read_bytes(), path.name
                    st.session_state['analysis_result'] = run_analysis(data, name)
                    st.session_state['playback_format'] = {'.mp3': 'audio/mpeg', '.flac': 'audio/flac', '.ogg': 'audio/ogg'}.get(Path(name).suffix.lower(), 'audio/wav')
            else:
                st.session_state['analysis_result'] = analyze(None)
        result = st.session_state.get('analysis_result', (EMPTY, '', None, None, None, []))
        if result[2] is not None:
            st.divider()
            st.markdown('Listen to the original')
            st.audio(result[2], format=st.session_state.get('playback_format', 'audio/wav'))
            st.markdown(result[1])
    with right:
        st.html(result[0])
        if result[3] is not None:
            responsive_plot(result[3], 'Inside the audio')
    st.divider()
    with st.expander('How the classifier used the embedding', expanded=True):
        st.markdown(CONTRIBUTION_GUIDE)
        if result[4] is not None:
            responsive_plot(result[4], 'Embedding contributions to the classifier')
        with st.expander('Inspect the ten strongest embedding dimensions'):
            numeric_table(['Embedding dimension', 'Average embedding value', 'Standardized value', 'Contribution (logit)'], result[5])


def render_results():
    metrics, predictions, confusion, distribution = evaluation_artifacts(hashlib.sha256((DEFAULT_OUTPUT / "metrics.json").read_bytes() + (ROOT / "showcase.py").read_bytes()).hexdigest())
    h = metrics['holdout']
    cm = h['confusion_matrix_true_rows_predicted_columns_human_ai']
    st.markdown(RESULTS_INTRO)
    st.markdown(f'**Validation accuracy: {metrics["validation"]["accuracy"]:.1%} | Evaluation accuracy: {h["accuracy"]:.1%}.** Accuracy is the fraction of recordings classified correctly; AI precision below is the fraction of AI predictions that were correct.')
    st.html(f'<div class="stat-grid"><div class="stat"><strong>{cm[1][1]} / {h["ai_tracks"]}</strong><span>AI recordings detected · recall {h["ai_recall"]:.1%}</span></div><div class="stat"><strong>{cm[0][1]} / {h["human_tracks"]}</strong><span>Human recordings falsely flagged · {h["human_false_positive_rate"]:.0%}</span></div><div class="stat"><strong>{h["ai_precision"]:.1%}</strong><span>AI precision on the evaluation set</span></div></div>')
    responsive_plot(confusion, 'Correct predictions and errors')
    st.markdown(SCORES_INTRO)
    responsive_plot(distribution, 'Score distributions by dataset label')
    errors = [[r['reference'], r['generator'] or 'Human reference', r['true_label'], r['predicted_label'], float(r['ai_score'])]
              for r in predictions if r['split'] == 'holdout' and r['true_label'] != r['predicted_label']]
    st.markdown('Recordings the encoder classifier got wrong')
    numeric_table(['Evaluation recording', 'Source label', 'Dataset label', 'Prediction', 'AI score'], errors)
    st.markdown(LIMITATIONS)


def main():
    st.set_page_config(page_title='AI Music Detector · Audio Lab', layout='wide', initial_sidebar_state='collapsed')
    st.html(stylesheet((ROOT / 'assets/streamlit.css').stat().st_mtime_ns))
    model_version=hashlib.sha256(MODEL_PATH.read_bytes() + Path(__file__).read_bytes() + (ROOT / 'showcase.py').read_bytes()).hexdigest()
    if st.session_state.get('analysis_model_version') != model_version:
        clear_result()
        st.session_state['analysis_model_version']=model_version
    st.html(HERO)
    analysis_tab, results_tab, how_tab = st.tabs(['Analyze audio', 'Model results', 'How it works'])
    with analysis_tab:
        render_analysis()
    with results_tab:
        render_results()
    with how_tab:
        st.markdown(HOW_IT_WORKS)


if __name__ == '__main__':
    main()
