"""Display copy for the portfolio demo."""

HERO = '<div class="hero"><h1>Listen. Measure. Inspect.</h1><p>Explore how our trained AI music detector reads a recording—and see the measurements behind its decision.</p><span class="small-note">Handcrafted features + logistic regression · exploratory baseline</span></div>'

RESULTS_INTRO = '## A real baseline, including its mistakes\nFour artist groups form this **exploratory holdout**: four human references and 12 generated recordings. The batch was inspected during development; it is not an untouched final test.'

SCORES_INTRO = '### Where the scores fall\nEach dot is one recording. The dashed line is the fixed 0.5 threshold. A human dot on the right is a false positive; an AI dot on the left is a missed detection.'

LIMITATIONS = '**What this does not establish:** unseen-generator performance, microphone robustness or certified authorship. Source bandwidth, encoding, offsets and the small dataset may affect predictions. Human false positives are the main measured weakness.'

HOW_IT_WORKS = '## From sound to a score\n**1 · Standardize the input.** Decode the recording, average its channels, resample to 24 kHz, and take the first ten seconds: 240,000 samples.\n\n**2 · Measure the sound.** RMS amplitude, zero crossings, spectral center, bandwidth and flatness. A mean and standard deviation for each give ten features.\n\n**3 · Apply what was learned.** The saved scaler uses training means and scales. Logistic regression combines ten weighted features with an intercept; a sigmoid maps that sum to an AI score.\n\n**4 · Make the baseline decision.** Scores at or above 0.5 produce “Likely AI-generated.” Lower scores produce “Likely human-made.” The score is not calibrated and there is no inconclusive rule yet.\n\n### The experiment behind this demo\n80 recordings across 20 provisional artist groups: **48 training, 16 validation, 16 holdout**. Related reference/artist recordings remain together. Only training data fits the scaler and classifier. Historical FMA recordings supply human-reference labels; Echoes TTA supplies generated labels from ACE-Step, AudioLDM and MusicGen.\n\n### Reading the visuals\nThe waveform and spectrogram show the exact processed clip used for prediction. The classifier receives the ten numeric summaries, rather than a spectrogram image. The feature chart shows each standardized feature multiplied by its learned weight; its bars plus the intercept equal the logit before the sigmoid.\n\n**Built with** NumPy, SciPy, librosa, scikit-learn and Streamlit. Dataset provenance, settings and limitations are recorded in the repository. No Hugging Face encoder is used in this version.\n'

CONTRIBUTION_GUIDE = 'Teal bars push toward human; amber bars push toward AI. These are exact weighted contributions in **logit units**, including the intercept. They show model influence—not causal evidence of AI generation.'

INPUT_GUIDANCE = '**10 seconds to 5 minutes.** Only the first 10 seconds are analyzed. Uploads are processed on the server running this app; microphone evaluation is deferred.'
